<a href="https://colab.research.google.com/github/subhajitmajumder/Python_Programming/blob/master/me_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy

- Numpy is one of the core libraries in the Pydata Ecosystem.
- This is mainly a Linear Algebra Library for Data Science.
- Almost all the libraries in Pydata Ecosystem are completely relying on Numpy Library.
- Numpy is also incredibly fast as it has bindings with C libraries.
- Numpy Library is completely depends on mainly two mathematical section i.e. Vectors & Matrices.
- Numpy has some great capabilities to provide random numbers.

**Installation of Numpy:** pip install Numpy



#Basic Numpy

###Numpy Arrays

In [0]:
import numpy as np

- **Casting a 1D array to numpy.**

In [0]:
list_1 = [1, 2, 3]

In [0]:
print(list_1)

[1, 2, 3]


In [0]:
arr = np.array(list_1) #Casting the array list_1 into numpy

In [0]:
arr

array([1, 2, 3])

- **Casting a list of lists into numpy array.**

In [0]:
list_2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [0]:
my_mat = np.array(list_2) #Casting a list of lists into numpy array
my_mat                    # Returning a 2D matrix.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
# We can create arrays a lot faster by using some numpy methods.

np.arange(0, 10) #create a 1D array from 0(starting) to 10(stop except this number)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.arange(0, 10, 2) #Third argument is step size which will provide equal distance numbers.

array([0, 2, 4, 6, 8])

In [0]:
np.zeros(3)   # arrays of all zeros single dimension

array([0., 0., 0.])

In [0]:
np.zeros((3, 4))  #Array of all zeros two dimensions using (x, y) tuple

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [0]:
np.ones(4)   #Array of all ones single dimesion

array([1., 1., 1., 1.])

In [0]:
np.ones((3, 5)) #Array of all ones two dimensions

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [0]:
np.linspace(0, 5, 10)  #Returns 10 evenly space points in a single dimension array from 0 to 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [0]:
np.linspace(0, 10, 10)   #This is a 1D array as the is only one square bracket.

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

####Difference between arange & linspace

Linspace use third argument as the number of points you want & arange takes the third argument as the steps size you want

In [0]:
#Identity Matrix in numpy.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
#Create arrays of random numbers.
np.random.rand(5)  # 1D array of random nnumbers uniformly distributed from 0 to 1

array([0.08267975, 0.6543017 , 0.76694025, 0.64222931, 0.21778136])

In [0]:
np.random.rand(5, 5) #2D arrays of random numbers.

array([[0.9667861 , 0.43994733, 0.46975839, 0.85910947, 0.16701383],
       [0.5414694 , 0.26605797, 0.61336015, 0.1439269 , 0.27641775],
       [0.41689575, 0.60818491, 0.82904518, 0.45343117, 0.43086765],
       [0.50480479, 0.20461238, 0.50527354, 0.37025542, 0.400191  ],
       [0.73766136, 0.98159623, 0.73004602, 0.75000697, 0.23074204]])

In [0]:
np.random.randn(5) #1D array of random numbers which is normally distributed. 

array([-0.57128487, -0.82455379,  0.76084408, -0.49114667,  0.76305192])

In [0]:
np.random.randn(4, 4) #2D array of random numbers

array([[ 2.82985772,  0.65877148, -0.38462988, -0.28599705],
       [-0.24282498, -0.41018641, -1.7133771 ,  1.89856972],
       [ 0.1997889 , -1.30459132, -2.42577906, -1.46347931],
       [ 1.21139772,  0.26814178,  0.08713465,  1.43461486]])

In [0]:
np.random.randint(1, 100) #print a random integer between lowest number and highest number excluding highest number

25

In [0]:
np.random.randint(1, 100, 10) #Print 10 random integers between lowest and highest number

array([48,  2,  6, 42, 82, 66, 63,  2, 17, 88])

In [0]:
arr_1 = np.arange(25)
print(arr_1)
arr_1.reshape(5, 5)  #Reshape a 1D array to 2D array.

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [0]:
#Find maximum,minimum,location of a random group of numbers.

rand_arr = np.random.randint(1, 100, 20)
print(rand_arr)
print(rand_arr.max())  #maximum number of this group of random numbers
print(rand_arr.min())  #minimum number of this group of random numbers
print(rand_arr.argmax()) #location of maximum number in this group
print(rand_arr.argmin()) #location of minimum number in the group

[22 17 15 22 91 61 54 41 13 52  9 74 21 73 55 76  2 64 25 74]
91
2
4
16


In [0]:
#Find shape of a vector or a matrix

arr_1.shape

(25,)

In [0]:
arr_2 = arr_1.reshape(5, 5)
print(arr_2)
arr_2.shape  #Showing the changed shape of arr_2 from arr_1

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


(5, 5)

In [0]:
# Find the datatype of an array.

arr_1.dtype

dtype('int64')

#Numpy Indexing & Selection

In [0]:
import numpy as np

#####Indexing

In [0]:
arr_2 = np.arange(0, 11)
print(arr_2)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [0]:
arr_2[7]  # 7th index starting form 0 in the list.

7

In [0]:
arr_2[1:4]  # multiple numbers starting from index 1 to index 4.This method is called slicing

array([1, 2, 3])

In [0]:
arr_2[:6] #starting from index 0 upto index 6 like arr_2[0:6]

array([0, 1, 2, 3, 4, 5])

In [0]:
arr_2[5:]  #Starting from a certain index to the last index like arr_2[5: 11]

array([ 5,  6,  7,  8,  9, 10])

In [0]:
#Broadcast or copy a specific number to some certain indexes.

arr_2[0: 5] = 100
arr_2

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

#####Indexing 2D array

In [0]:
 arr_2D = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
 arr_2D

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [0]:
#Indexing (first method double bracket).

arr_2D[0][1]  #first index for row(starts from 0) and 2nd index for column(starts from 0)

1

- Get the number 8 from the matrix

In [0]:
arr_2D[2][2]

8

- Get the entire row of a certain index 

In [0]:
arr_2D[0]

array([0, 1, 2])

In [0]:
#Indexing (second method & best method single bracket comma)

arr_2D[2, 2]

8

- Grab certain matrices from this matrix

In [0]:
#Get top right corner of the matrix arr_2D

print(arr_2D)
print("\n")
arr_2D[:2, 1:] #Grab everything from row 0 and 1 (2 excluded) & everything from column 1 

[[0 1 2]
 [3 4 5]
 [6 7 8]]




array([[1, 2],
       [4, 5]])

In [0]:
#Grab bottom rows at a whole.

print(arr_2D)
print("\n")
arr_2D[1:]

[[0 1 2]
 [3 4 5]
 [6 7 8]]




array([[3, 4, 5],
       [6, 7, 8]])

- Conditional Selection

In [0]:
arr_1 = np.arange(0, 11)
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
bool_arr = arr_1 > 5   #Get boolean return for this condition

In [0]:
arr_1[bool_arr]  #Only returns the True values in this array

array([ 6,  7,  8,  9, 10])

- Conditional selection with syntax notation

In [0]:
arr_1[arr_1 > 5]  #Return same value as above using syntax notation

array([ 6,  7,  8,  9, 10])

- Use multiple functions in a same line

In [0]:
arr_2d = np.arange(0, 50).reshape(5, 10)  #.arange takes numbers from 0 to 50 and .reshape creates it in 2D array
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [0]:
# Grab [[13, 14], [23, 24]] from the 2D array

arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

#Numpy Operations

In [0]:
import numpy as np

- **Array with array**

In [2]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
arr + arr  #Adding the array with the same array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [0]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [0]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

- **Array with Scalar**

In [0]:
arr + 100 #Can add a scalar value with the array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [0]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [0]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

- **Universal Array Functions**

In [0]:
np.sqrt(arr)  #Square root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [0]:
np.exp(arr) #Exponent

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [0]:
np.max(arr)  # Max

10

In [0]:
np.sin(arr) #Sin values

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [0]:
np.log(arr)  #As log 0 is negative undefined so there is a warning.

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

- Check all the detailed references at the link below.

https://docs.scipy.org/doc/numpy/reference/ufuncs.html

In [3]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566,
        0.64836083])