<a href="https://colab.research.google.com/github/subhajitmajumder/python_program/blob/master/NumPy_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

# Working with list and compare time for diffrent coding style.

In [0]:
%%time
N = 100000000
list_ = list(range(N))
for i in range(N):
  list_[i] = list_[i] * list_[i]

CPU times: user 19.3 s, sys: 2.58 s, total: 21.9 s
Wall time: 22 s


In [0]:
%%time
list_ = list(range(N))
list_ = [item * item for item in list_]

CPU times: user 9.06 s, sys: 5 s, total: 14.1 s
Wall time: 14.1 s


In [0]:
%%time
list_ = list(range(N))
list_ = map(lambda x: x * x, list_)

CPU times: user 2.37 s, sys: 1.48 s, total: 3.85 s
Wall time: 3.83 s


####Add all numbers in a list


In [0]:
%%time
list_ = list(range(N))
list_sum = 0
for item in list_:
  list_sum += item

CPU times: user 11.7 s, sys: 1.49 s, total: 13.2 s
Wall time: 13.2 s


In [0]:
%%time
list_ = list(range(N))
list_sum = sum(list_)

CPU times: user 2.97 s, sys: 1.5 s, total: 4.47 s
Wall time: 4.46 s


In [0]:
%%time
arr = np.arange(N)
arr = arr * arr

CPU times: user 394 ms, sys: 12.6 ms, total: 407 ms
Wall time: 423 ms


In [0]:
%%time
arr = np.arange(N)
arr_sum = np.sum(arr)

CPU times: user 288 ms, sys: 8.32 ms, total: 296 ms
Wall time: 299 ms


In [0]:
#We can create a list through numpy like this.
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [0]:
#Another way to create a list through numpy.
arr = np.array([0,2,4,6,8])
print(arr)

[0 2 4 6 8]


In [0]:
#To show the datatype.
arr.dtype

dtype('int64')

In [0]:
#To know the dimension
arr.ndim

1

In [0]:
arr.shape

(5,)

In [0]:
arr.size


5

In [0]:
#itemsize is no. of bytes need to store one number.
arr.itemsize

8

In [0]:
#Create 2D array
arr2d = np.array([
                  [1, 2, 3],
                  [4, 5, 6]
])

In [0]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
arr2d.ndim

2

In [0]:
arr2d.shape

(2, 3)

In [0]:
arr2d.size

6

In [0]:
#tow planes 3D array
arr3d = np.array([
                  [
                   [1, 2, 3],
                   [4, 5, 6]
                  ],
                  [
                   [7, 8, 9],
                   [10, 11, 12]
                  ]
])

In [0]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [0]:
arr3d.shape

(2, 2, 3)

In [0]:
arr3d.ndim

3

In [0]:
arr3d.size

12

In [0]:
#We can create n array with constant value.
 np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [0]:
#To create different values.
990 * np.ones((2, 3, 4))

array([[[990., 990., 990., 990.],
        [990., 990., 990., 990.],
        [990., 990., 990., 990.]],

       [[990., 990., 990., 990.],
        [990., 990., 990., 990.],
        [990., 990., 990., 990.]]])

In [0]:
#We can create all the values zeros
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

#### Actually we need to create random data so that we can experiment different functionalities.

In [0]:
#Create random data
np.random.randn(2, 3) #Normal Distribution

array([[ 0.22484937,  0.13555232, -0.42613144],
       [-1.29543732,  1.76495356,  1.14630117]])

In [0]:
#Uniformly sampled random numbers between 0 and 1
np.random.rand(2, 3)

array([[0.57175821, 0.90100133, 0.45757177],
       [0.88121239, 0.77993348, 0.34283797]])

In [0]:
np.random.rand(10, 1)

array([[0.96479207],
       [0.23626871],
       [0.76714407],
       [0.61070056],
       [0.05562545],
       [0.09671016],
       [0.76345877],
       [0.6733095 ],
       [0.64874222],
       [0.96921206]])

In [0]:
#random integers between two numbers.
np.random.randint(0, 100, (2, 3))

array([[75, 56, 14],
       [97, 67, 96]])

In [0]:
#integers between two numbers with step size.
np.arange(7, 71, 7)

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [0]:
# integers between two numbers with selected spaces.
np.linspace(7, 70, 10)

array([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70.])

In [0]:
#Creating arrays of other dtypes.
np.array([True, False, True, False])

array([ True, False,  True, False])

In [0]:
 np.array(['2.5', 'subhajit', 'rob', '4.8'])

array(['2.5', 'subhajit', 'rob', '4.8'], dtype='<U8')

In [0]:
#Convert a string to float.
str_arr = np.array(['2.5', '3.5', '1.3'])
arr = np.array(str_arr, dtype='float')
arr

array([2.5, 3.5, 1.3])

### Numpy Oerations

In [0]:
arr1 = np.random.rand(3, 4)
arr2 = np.random.rand(3, 4)

In [0]:
arr1

array([[0.65422855, 0.7314319 , 0.16871506, 0.13715512],
       [0.86855555, 0.27239641, 0.3398476 , 0.07465505],
       [0.40280518, 0.59807562, 0.75063905, 0.28890579]])

In [0]:
arr2

array([[0.2957776 , 0.56233709, 0.07582681, 0.02224136],
       [0.47273652, 0.6301707 , 0.17022233, 0.13807333],
       [0.15612429, 0.81898801, 0.37546166, 0.66318077]])

In [0]:
arr1 + arr2

array([[0.95000614, 1.29376899, 0.24454187, 0.15939648],
       [1.34129207, 0.9025671 , 0.51006994, 0.21272838],
       [0.55892947, 1.41706363, 1.12610071, 0.95208656]])

In [0]:
arr1 - arr2

array([[ 0.35845095,  0.16909481,  0.09288825,  0.11491376],
       [ 0.39581903, -0.35777429,  0.16962527, -0.06341828],
       [ 0.24668089, -0.2209124 ,  0.3751774 , -0.37427498]])

In [0]:
arr1 * arr2

array([[0.19350615, 0.41131128, 0.01279313, 0.00305052],
       [0.41059793, 0.17165623, 0.05784965, 0.01030787],
       [0.06288767, 0.48981676, 0.28183618, 0.19159676]])

In [0]:
arr1/arr2

array([[2.21189351, 1.30070008, 2.22500533, 6.16666982],
       [1.83729311, 0.43225813, 1.99649242, 0.54069129],
       [2.58002889, 0.73026175, 1.9992429 , 0.43563656]])

In [0]:
#Exponentiation
np.exp(arr1)

array([[1.92365793, 2.07805404, 1.18378278, 1.14700606],
       [2.38346557, 1.31310742, 1.40473349, 1.0775124 ],
       [1.49601541, 1.81861572, 2.11835333, 1.33496595]])

In [0]:
#Logarithm
np.log(arr1)

array([[-0.42429853, -0.31275116, -1.77954402, -1.98664271],
       [-0.14092374, -1.3004969 , -1.07925799, -2.59487712],
       [-0.90930225, -0.51403808, -0.28683036, -1.24165464]])

In [0]:
#Sine Function
np.sin(arr1)

array([[0.60854726, 0.66793596, 0.16791579, 0.13672551],
       [0.76339672, 0.26904025, 0.33334341, 0.07458572],
       [0.39200055, 0.56305317, 0.68210621, 0.28490353]])

In [0]:
#Cosine Function
np.cos(arr1)

array([[0.79351763, 0.74421875, 0.98580134, 0.99060897],
       [0.64592991, 0.96312893, 0.94280548, 0.99721461],
       [0.91996498, 0.82642067, 0.73125312, 0.95855619]])

In [0]:
#Square root
np.sqrt(arr1)

array([[0.80884396, 0.85523792, 0.41074939, 0.3703446 ],
       [0.93196328, 0.52191609, 0.58296449, 0.27323076],
       [0.63466935, 0.77335349, 0.86639428, 0.53749957]])

In [0]:
#Inverse Function
arr_inv = 1 / arr1
arr_inv

array([[ 1.52851783,  1.36718129,  5.92715316,  7.29101456],
       [ 1.15133684,  3.67112039,  2.94249539, 13.39494134],
       [ 2.48258971,  1.67202937,  1.3321982 ,  3.46133598]])

In [0]:
arr3 = np.zeros((3, 5))

In [0]:
arr3_inv = 1/arr3
arr3_inv

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [0]:
#Checking all the values are infinity or not
np.isinf(arr3_inv)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

### Indexing

In [0]:
arr3d = np.array([
                  [
                   [1, 2, 3],
                  [4, 5, 6]
                   ],
                  [
                   [7, 8, 9],
                   [10, 11, 12]
                  ]
])

In [0]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [0]:
#Indexing a cell in the 3D array.
arr3d[1, 0, 0]

7

In [0]:
#Slicing a 3D array
arr3d[0, :, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
arr3d[:, 1, :]

array([[ 4,  5,  6],
       [10, 11, 12]])

In the case of slicing whichever is the value after colon, python takes the value previous to the last value

In [0]:
arr3d[:, :, 0:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In the above case 0:2 means from 0th column except 2nd column..

We can choose indices with our preferrable values in the array.
Say, we neeed to choose those indices where the values are even.We can do it very efficiently using NumPy.
In the example below, it will actually show the boolean values.

In [0]:
arr3d % 2 == 0

array([[[False,  True, False],
        [ True, False,  True]],

       [[False,  True, False],
        [ True, False,  True]]])

Also we can get the values of all values of our desireable preferances.

In [0]:
arr3d[arr3d % 2 == 0] #Get a 1D array

array([ 2,  4,  6,  8, 10, 12])

Also e can take multiple conditions

In [0]:
arr3d[(arr3d % 2 == 1) & (arr3d > 3)]

array([ 5,  7,  9, 11])

In [0]:
arr_slice = arr3d[:, :, 0:2]

In [0]:
print(type(arr_slice))

<class 'numpy.ndarray'>


In [0]:
arr_slice.ndim

3

In [0]:
arr_slice.shape

(2, 2, 2)

In [0]:
arr_slice[0, 0, 1]

2

In [0]:
#Change value in arr_slice
arr_slice[0, 0, 0] = 1729
arr_slice

array([[[1729,    2],
        [   4,    5]],

       [[   7,    8],
        [  10,   11]]])

SO if we take a slice of original array and modify the slice then it will reflex the original array also.

In [0]:
arr3d

array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

But if we copy the slice from the original array and then change some values of that sliced array, then the original array will remain unchanged.

In [0]:
arr_slice = np.copy(arr3d[:, :, 0:2])

In [0]:
arr_slice[0, 0, 0] = 1

In [0]:
arr_slice

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [0]:
arr3d

array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

Another way of indexing

In [0]:
arr = np.random.randint(0, 10, (5))
arr

array([8, 6, 0, 4, 1])

In [0]:
my_indices = [1, 3, 4]

In [0]:
arr[my_indices]

array([6, 4, 1])

Take a square and take one fourth circle inside a square whose radius is equals to side of the square.Now take multiple points inside the square and the circle and find out the distance between these points and the origin.
Also find out how many points are the outside the circle.
Try it for multiple dimensions.

In [0]:
ndim = 2
npoints = 100000
points = np.random.rand(npoints, ndim)

In [0]:
points[0:10, :]

array([[0.42698156, 0.85383268],
       [0.08396271, 0.23516042],
       [0.58105757, 0.52903472],
       [0.6231372 , 0.95395518],
       [0.19492511, 0.25206311],
       [0.63767652, 0.78461864],
       [0.90269137, 0.91007844],
       [0.90696249, 0.57228636],
       [0.02768424, 0.90761215],
       [0.0589314 , 0.87833051]])

In [0]:
distant_from_origin = np.zeros((npoints, 1))
outside_points = 0
distant_from_origin[0:10]

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [0]:
%%time
for i in range(npoints):
  for j in range(ndim):
    distant_from_origin[i] += points[i, j] ** 2
  distant_from_origin[i] = np.sqrt(distant_from_origin[i])
  if distant_from_origin[i] > 1:
    outside_points += 1
print(outside_points)

21314
CPU times: user 1.24 s, sys: 0 ns, total: 1.24 s
Wall time: 1.24 s


In [0]:
outside_points

21595

In [0]:
%%time
sqr_points = points * points
distant_from_origin = np.sqrt(np.sum(sqr_points, axis = 1))
outside_points = np.sum(distant_from_origin>1)
print(outside_points)

21595
CPU times: user 3.78 ms, sys: 109 µs, total: 3.89 ms
Wall time: 4.07 ms


In [0]:
%%time
outside_points = np.sum(np.sqrt(np.sum(points * points, axis = 1)) > 1)
print(outside_points)

21595
CPU times: user 4.91 ms, sys: 0 ns, total: 4.91 ms
Wall time: 3.8 ms


In [0]:
%%time
def area_outside_circle(npoints, ndim):
  points = np.random.rand(npoints, ndim)
  outside_points = np.sum(np.sqrt(np.sum(points * points, axis = 1)) > 1)
  # outside_points = outside_points/npoints
  return outside_points

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 8.11 µs


In [0]:
area_outside_circle(100000, 2)

21444

In [0]:
for i in range(2, 10):
  print(area_outside_circle(1000000, i))

215111
477093
692165
835341
919518
962909
983974
993606


## Broadcasting

In [0]:
arr1 = np.arange(6)

In [0]:
arr1

array([0, 1, 2, 3, 4, 5])

In [0]:
#reshaping arr1
arr1 = arr1.reshape(3, 2)
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [0]:
arr2 = np.arange(6).reshape(3, 2)
arr2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [0]:
arr1 + arr2

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [0]:
arr2[0]

array([0, 1])

In [0]:
arr2[0].reshape(1, 2)

array([[0, 1]])

In [0]:
arr1 + arr2[0].reshape((1, 2)) # (3, 2) + (1, 2)

array([[0, 2],
       [2, 4],
       [4, 6]])

In [0]:
arr2[:, 0].reshape(3, 1)

array([[0],
       [2],
       [4]])

In [0]:
arr1 + arr2[:, 0].reshape(3, 1) #(3, 2) + (3, 1)

array([[0, 1],
       [4, 5],
       [8, 9]])

In [0]:
arr1 = np.arange(24).reshape(2, 3, 4)
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [0]:
arr2 = np.ones((1, 4))
arr2

array([[1., 1., 1., 1.]])

In [0]:
arr1 + arr2 # (2, 3, 4) + (1, 4)

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]]])

In [0]:
arr1 = np.arange(4)
arr2 = np.arange(5)

In [0]:
arr1

array([0, 1, 2, 3])

In [0]:
arr2

array([0, 1, 2, 3, 4])

In [0]:
arr1 + arr2

ValueError: ignored

In [0]:
arr1 + arr2.reshape(5, 1) #(4) + (5, 1)

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

We can use 'T' or transpose instead of reshape.

In [0]:
arr = np.random.rand(3, 3)
arr

array([[0.49159453, 0.56502228, 0.51712972],
       [0.31138843, 0.27771994, 0.41590589],
       [0.5568924 , 0.3925546 , 0.95217438]])

In [0]:
arr.T

array([[0.49159453, 0.31138843, 0.5568924 ],
       [0.56502228, 0.27771994, 0.3925546 ],
       [0.51712972, 0.41590589, 0.95217438]])

## File Handling

In [0]:
planets_small = np.loadtxt("planets_small.txt")

ValueError: ignored

We cant convert a string value to a float.So we need to alter or skip some rows

In [0]:
planets_small = np.loadtxt("planets_small.txt",
                           skiprows = 1)

ValueError: ignored

In [0]:
planets_small = np.loadtxt("planets_small.txt",
                           skiprows = 1,
                           usecols = (1, 2, 3, 4, 5, 6, 7, 8, 9))

In [0]:
planets_small

array([[3.3000e-01, 4.8700e+00, 5.9700e+00, 6.4200e-01, 1.8980e+03,
        5.6800e+02, 8.6800e+01, 1.0200e+02, 1.4600e-02],
       [5.7900e+01, 1.0820e+02, 1.4960e+02, 2.2790e+02, 7.7860e+02,
        1.4335e+03, 2.8725e+03, 4.4951e+03, 5.9064e+03],
       [4.2226e+03, 2.8020e+03, 2.4000e+01, 2.4700e+01, 9.9000e+00,
        1.0700e+01, 1.7200e+01, 1.6100e+01, 1.5330e+02]])

In [0]:
planets_small.shape

(3, 9)

In [0]:
planets = np.loadtxt("planets.txt",
                           skiprows = 1,
                           usecols = (1, 2, 3, 4, 5, 6, 7, 8, 9))

ValueError: ignored

In [0]:
planets = np.genfromtxt("planets.txt",
                        skip_header = 1,
                        usecols = (1,2,3,4,5,6,7,8,9))

planets

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [0]:
planets.shape

(20, 9)

In [0]:
np.isnan(planets)

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, 

In [0]:
planets_new = np.nan_to_num(planets, nan=-1)

planets_new

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [0]:
np.savetxt('planets_new.txt', planets_new,
           delimiter = ',')

This above saving process is human readable.We can also save a file which can be efficiently processed by NumPy.

The extension of these types of files are .npy

Showing below

In [0]:
np.save("planets_new", planets_new)

In [0]:
!ls -lh

total 24K
-rw-r--r-- 1 root root 1.6K Apr  2 15:14 planets_new.npy
-rw-r--r-- 1 root root 4.5K Apr  2 15:11 planets_new.txt
-rw-r--r-- 1 root root  255 Apr  2 14:42 planets_small.txt
-rw-r--r-- 1 root root 1.5K Apr  2 14:42 planets.txt
drwxr-xr-x 1 root root 4.0K Mar 18 16:23 sample_data


NumPy can also store multi dimensions arrays in a file.

In [0]:
arr1 = np.random.rand(4000, 5)
arr2 = np.random.rand(2000, 10)
arr3 = np.random.rand(20, 10000000)

In [0]:
np.savez("many_arrs", arr1, arr2, arr3)

We can load a file using NumPy.

In [0]:
arrs = np.load('many_arrs.npz')

In [0]:
type(arrs)

numpy.lib.npyio.NpzFile

In [0]:
arrs.files

['arr_0', 'arr_1', 'arr_2']

In [0]:
arrs['arr_0']

array([[0.73439302, 0.41103188, 0.4869391 , 0.06111899, 0.86826554],
       [0.93887987, 0.88612553, 0.10915058, 0.94278013, 0.70807791],
       [0.25724949, 0.03536027, 0.00252645, 0.66134795, 0.59571113],
       ...,
       [0.66935552, 0.06138788, 0.53151244, 0.45534417, 0.79967474],
       [0.33828853, 0.86332615, 0.53587869, 0.93618378, 0.81859597],
       [0.47530516, 0.37834263, 0.14397057, 0.13253311, 0.98240419]])

In [0]:
arrs['arr_2'].shape

(20, 10000000)

In [0]:
np.savez_compressed('many_arrs_compressed',
                    arr1, arr2, arr3)

In [0]:
!ls -lh

total 2.9G
-rw-r--r-- 1 root root 1.5G Apr  2 16:17 many_arrs_compressed.npz
-rw-r--r-- 1 root root 1.5G Apr  2 16:06 many_arrs.npz
-rw-r--r-- 1 root root 1.6K Apr  2 15:14 planets_new.npy
-rw-r--r-- 1 root root 4.5K Apr  2 15:11 planets_new.txt
-rw-r--r-- 1 root root  255 Apr  2 14:42 planets_small.txt
-rw-r--r-- 1 root root 1.5K Apr  2 14:42 planets.txt
drwxr-xr-x 1 root root 4.0K Mar 18 16:23 sample_data


In [0]:
arr4 = np.zeros((10000, 10000))

In [0]:
np.savez("zeros", arr4)

In [0]:
np.savez_compressed("zeros_compressed", arr4)

In [0]:
!ls -lh+

total 3.7G
-rw-r--r-- 1 root root 1.5G Apr  2 16:17 many_arrs_compressed.npz
-rw-r--r-- 1 root root 1.5G Apr  2 16:06 many_arrs.npz
-rw-r--r-- 1 root root 1.6K Apr  2 15:14 planets_new.npy
-rw-r--r-- 1 root root 4.5K Apr  2 15:11 planets_new.txt
-rw-r--r-- 1 root root  255 Apr  2 14:42 planets_small.txt
-rw-r--r-- 1 root root 1.5K Apr  2 14:42 planets.txt
drwxr-xr-x 1 root root 4.0K Mar 18 16:23 sample_data
-rw-r--r-- 1 root root 760K Apr  2 16:25 zeros_compressed.npz
-rw-r--r-- 1 root root 763M Apr  2 16:25 zeros.npz


# NumPy for Stats

In [0]:
arr = np.random.rand(100000,)

In [3]:
#find minimum in the array.
np.amin(arr)

2.108194081285042e-05

In [4]:
#find max in the array
np.amax(arr)

0.9999920474231536

In [5]:
#Find mean
np.mean(arr)

0.5008370496631501

In [6]:
#FInd Variance
np.var(arr)

0.08304246354063567

In [7]:
#Find STD
np.std(arr)

0.28817089294485604

In [8]:
#Find median
np.median(arr)

0.5014062405394335

In [9]:
#Find percentile
np.percentile(arr, 50)

0.5014062405394335

In [10]:
np.percentile(arr, 10)

0.1004682999992114

In [11]:
np.percentile(arr, 90)

0.8995597360863464

One way to find IQR

In [12]:
%%time
iqr = np.percentile(arr, 75) - np.percentile(arr, 25)

CPU times: user 2.86 ms, sys: 951 µs, total: 3.81 ms
Wall time: 3.91 ms


In [13]:
iqr

0.49796087505790687

Another way to find IQR.This process can save some times.

In [14]:
%%time
quartile = np.percentile(arr, (25, 75))
iqr1 = quartile[1] - quartile[0]

CPU times: user 3.21 ms, sys: 733 µs, total: 3.94 ms
Wall time: 3.5 ms


In [15]:
iqr1

0.49796087505790687

In [16]:
print(quartile)

[0.25239105 0.75035192]


In [17]:
# Compute z score
z_score = (arr - np.mean(arr)) / np.std(arr)
z_score

array([-1.60565298,  0.46215943,  1.20251614, ..., -1.13688069,
       -0.13376939,  1.00327503])

In [18]:
#We can create histogram through numpy
np.histogram(arr)

(array([ 9953,  9889,  9868, 10136, 10031, 10065, 10030,  9984, 10088,
         9956]),
 array([2.10819408e-05, 1.00018178e-01, 2.00015275e-01, 3.00012372e-01,
        4.00009468e-01, 5.00006565e-01, 6.00003661e-01, 7.00000758e-01,
        7.99997854e-01, 8.99994951e-01, 9.99992047e-01]))

In [19]:
np.histogram(arr, bins= 5)

(array([19842, 20004, 20096, 20014, 20044]),
 array([2.10819408e-05, 2.00015275e-01, 4.00009468e-01, 6.00003661e-01,
        7.99997854e-01, 9.99992047e-01]))

In [20]:
np.histogram(arr, bins = [0, 0.25, 0.50, 0.75, 1])

(array([24746, 25130, 25098, 25026]), array([0.  , 0.25, 0.5 , 0.75, 1.  ]))

In [21]:
#Mapping the points with bin numbers or in which bins range the numbers are lying
bins = [0, 0.25, 0.50, 0.75, 1]
np.digitize(arr, bins)


array([1, 3, 4, ..., 1, 2, 4])

In [23]:
# example of points and bins mapping

arr1 = [2, 2, 4, 1, 8, 8, 6, 9, 2, 3, 1, 0, 10]
bins = [0, 6, 10]
np.digitize(arr1, bins)

array([1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 3])

In the above example 2 lies in 0-6 bin, 8 lies in 6-10 bin and so on

We have seen 6 lies in second bin i.e in the normal case the bins include the left side but exclude the right side.

By the below technique right side is also got included.

In [25]:
np.digitize(arr1, bins, right=True)

array([1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 0, 2])

In [0]:
arr1 = np.random.randint(50, 80, 100) #weight
arr2 = np.random.randint(150, 185, 100) #height
arr3 = np.random.randint(17, 22, 100) #age

We can concatenate all these arrays.

In [31]:
arr_concat = np.concatenate((arr1, arr2, arr3))
arr_concat

array([ 71,  77,  65,  67,  71,  51,  67,  69,  51,  52,  69,  57,  56,
        51,  68,  76,  73,  60,  63,  64,  67,  70,  61,  70,  73,  56,
        73,  73,  54,  53,  79,  73,  75,  70,  65,  77,  53,  72,  69,
        70,  75,  59,  53,  79,  72,  50,  54,  66,  58,  75,  55,  58,
        52,  65,  51,  69,  74,  60,  63,  70,  70,  79,  64,  53,  67,
        69,  63,  73,  60,  64,  63,  55,  54,  70,  74,  60,  72,  57,
        74,  79,  63,  73,  63,  62,  55,  56,  59,  64,  62,  76,  58,
        72,  77,  56,  51,  69,  74,  69,  64,  72, 163, 151, 180, 178,
       177, 174, 161, 151, 153, 183, 178, 170, 167, 150, 153, 155, 176,
       182, 170, 151, 154, 166, 175, 176, 150, 166, 158, 172, 170, 154,
       162, 150, 171, 184, 166, 177, 184, 169, 162, 182, 173, 184, 161,
       177, 174, 167, 176, 164, 166, 163, 170, 167, 157, 173, 157, 163,
       160, 177, 150, 176, 175, 159, 177, 175, 166, 181, 170, 177, 154,
       157, 165, 173, 163, 175, 156, 166, 176, 183, 159, 154, 16

In [32]:
arr_concat.shape

(300,)

Now in this case there is a single list where all the values are one after another.

But we need all these values in a tabular format.

In [35]:
np.vstack((arr1, arr2, arr3)).shape

(3, 100)

By using vstack or vertically stack above, we can create a matrix where all the data are sorted in 3 rows and 100 columns each

In [0]:
arr_2d = np.vstack((arr1, arr2, arr3))

Now we can solve some specific questions related to original datasets i,e, arr1, arr2 and so on

In [39]:
# Finding the minimum of specific rows across columns
np.amin(arr_2d, axis = 1)

array([ 50, 150,  17])

# Rules of Statistics

### Mean substracted array has zero mean

In [0]:
arr = np.random.rand(1000)

In [0]:
mean = np.mean(arr)

In [0]:
arr1 = arr - mean

In [6]:
np.mean(arr1)

2.3092638912203255e-17

### Computing mean with smaller set of values

In [0]:
arr = np.random.rand(1000)

In [0]:
for k in range(1, 50):
  arr1 = arr[0:k]
  print(k, np.mean(arr1))

In [0]:
means = np.cumsum(arr)/np.arange(1, 1001)

In [9]:
means[0:15]

array([0.32072819, 0.44151423, 0.50067646, 0.48131028, 0.53572811,
       0.50609785, 0.47206634, 0.43940288, 0.4435453 , 0.41584294,
       0.38691597, 0.42453162, 0.39988108, 0.3926617 , 0.41020834])

### Effects of outliers on mean and median

In [29]:
arr = np.random.randint(1, 100, 100)
arr.shape

(100,)

In [30]:
np.mean(arr)

48.51

In [31]:
np.median(arr)

49.0

In [0]:
arr = np.append(arr, [1000, 2000])

In [33]:
arr.shape

(102,)

In [36]:
np.mean(arr) #As mean is very sensitive to outliers so the mean has changed significantly.

76.97058823529412

In [37]:
np.median(arr)

50.5

### Effect of scaling arrays on mean and median.

In [0]:
arr = np.random.rand(100)

In [39]:
np.mean(arr)

0.506480747970444

In [40]:
np.median(arr)

0.4998662246893649

In [0]:
arr1 = 2.5 * arr + 0.65

In [42]:
print(np.mean(arr1), 2.5 * np.mean(arr) + 0.65)

1.9162018699261096 1.9162018699261099


In [43]:
print(np.median(arr1), 2.5 * np.median(arr) + 0.65)

1.8996655617234124 1.8996655617234124


In [44]:
print(np.var(arr1), 2.5 * np.var(arr) + 0.65)

0.4773289283579097 0.840931571343164
